### ISSUE TITLE
Bug: Invalid Token?

### ISSUE THREAD

**Issue by paintballlaws** [Crypta-Eve/seat-strict#4] opened 2021-08-12 23:09 UTC
So not sure if this is on seat side or the plugin side but if you have a character that was in seat and you biomassed them they still show up in seat for an admin and the character still counts as being a technical invalid token towards that character and it cannot be removed/unlinked in seat. So as you can guess you will get removed from groups and so forth...

**Comment by Crypta-Eve** [comment] 2021-08-13 23:07
Hmm.. That is intended behaviour of seat that I hadn't accounted for... 

Would this solution work for you:

SeAT Strict creates a new dummy user (maybe called BIOMASSED) or something?
You as an admin can then manually move the biomassed character over to that dummy user.

**Comment by paintballlaws** [comment] 2021-08-14 03:03
So two things I do actually like that idea kind of because it would allow me to still see biomassed characters the only thing is I wouldn't know whos they were originally but it still works for record keeping kind of. Secondly I just had a guy show me that you can actually delete characters now thru the All Characters screen so don't know when that got added to seat but I can also use that to get rid of them entirely. So I don't know if we could come up with a solution either on the seat side to make it better or via the plugin but would love more feedback.

**Comment by Crypta-Eve** [comment] 2021-09-02 18:27
resolved by ignoring all characters that are reported by ESI as biomassed. https://github.com/Crypta-Eve/seat-strict/commit/8765aa2d6a20f2dc86156c082291d3b2ec4a583a

**Closed as completed by Crypta-Eve** 2021-09-02 18:27 UTC
Labels: bug, enhancement
